# Generated by Django 2.1.7 on 2019-04-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='fichier',
        ),
    ]
